import { FIREBASE_CONFIG } from "../utils/firebase";

const FIREBASE = {
  API_KEY: FIREBASE_CONFIG.API_KEY,
  AUTH_DOMAIN: FIREBASE_CONFIG.AUTH_DOMAIN,
  PROJECT_ID: FIREBASE_CONFIG.PROJECT_ID,
  STORAGE_BUCKET: FIREBASE_CONFIG.STORAGE_BUCKET,
  MESSAGING_SENDER_ID: FIREBASE_CONFIG.MESSAGING_SENDER_ID,
  APP_ID: FIREBASE_CONFIG.APP_ID,
};

const firebaseConfig = {
  apiKey: FIREBASE.API_KEY,
  authDomain: FIREBASE.AUTH_DOMAIN,
  projectId: FIREBASE.PROJECT_ID,
  storageBucket: FIREBASE.STORAGE_BUCKET,
  messagingSenderId: FIREBASE.MESSAGING_SENDER_ID,
  appId: FIREBASE.APP_ID,
};

export { FIREBASE, firebaseConfig };
